CREATE USER PAYMENT1 IDENTIFIED BY PAYMENT1;
ALTER USER PAYMENT1
DEFAULT TABLESPACE SYSTEM
TEMPORARY TABLESPACE TEMP
ACCOUNT UNLOCK;

-- QUOTAS
ALTER USER PAYMENT1 QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT CONNECT, RESOURCE TO PAYMENT1;
ALTER USER PAYMENT1 DEFAULT ROLE CONNECT, RESOURCE;

-- GRANT
GRANT ALTER USER TO PAYMENT1;
GRANT CREATE TABLE, CREATE VIEW TO PAYMENT1;
GRANT GRANT ANY OBJECT PRIVILEGE, GRANT ANY ROLE, GRANT ANY PRIVILEGE TO PAYMENT1;