INSERT INTO PAYMENT1.CUSTOMER(CUSTOMER_ID, FIRST_NAME, LAST_NAME, CARD_NUMBER) VALUES
(1, 'Ivan', 'Ivanov', 2341);
INSERT INTO PAYMENT1.CUSTOMER(CUSTOMER_ID, FIRST_NAME, LAST_NAME, CARD_NUMBER) VALUES
(2, 'Alice','Melnikova', 31743);
INSERT INTO PAYMENT1.CUSTOMER(CUSTOMER_ID, FIRST_NAME, LAST_NAME, CARD_NUMBER) VALUES
(3,  'Vladimir', 'Sidorov', 7575);

INSERT INTO PAYMENT1.PRODUCT(PRODUCT_ID, NAME_PRODUCT, COST_PRODUCT) VALUES
(1, 'TV', 10000);
INSERT INTO PAYMENT1.PRODUCT(PRODUCT_ID, NAME_PRODUCT, COST_PRODUCT) VALUES
(2, 'Computer', 30000.5);
INSERT INTO PAYMENT1.PRODUCT(PRODUCT_ID, NAME_PRODUCT, COST_PRODUCT) VALUES
(3, 'Phone', 9800);

INSERT INTO PAYMENT1.CUSTOMER_ORDER(ORDER_ID, DATE_ORDER, CUSTOMER_ID) VALUES
(1, '10/03/2016', 1);
INSERT INTO PAYMENT1.CUSTOMER_ORDER(ORDER_ID, DATE_ORDER, CUSTOMER_ID) VALUES
(2, '10/02/2016', 2);

INSERT INTO PAYMENT1.ORDER_PRODUCT(ID, ORDER_ID, PRODUCT_ID) VALUES
(1, 1, 2);
INSERT INTO PAYMENT1.ORDER_PRODUCT(ID, ORDER_ID, PRODUCT_ID) VALUES
(2, 1, 3);
INSERT INTO PAYMENT1.ORDER_PRODUCT(ID, ORDER_ID, PRODUCT_ID) VALUES
(3, 2, 1);
INSERT INTO PAYMENT1.ORDER_PRODUCT(ID, ORDER_ID, PRODUCT_ID) VALUES
(4, 2, 3);
